config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  devise_for :customers
  resources :products
  resources :orderlines
  resources :orders

  root 'products#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  acts_as_orderer

  has_many :orders
  has_many :products
  has_many :orderlines

end

app/models/order.rb
class Order < ActiveRecord::Base

	has_many :orderlines
	has_many :products
	belongs_to :customer

end

app/models/orderline.rb
class Orderline < ActiveRecord::Base

	has_many :products
	belongs_to :order
	belongs_to :customer

end

app/models/product.rb
class Product < ActiveRecord::Base

	acts_as_sellable

	belongs_to :orderline
	belongs_to :order
	belongs_to :customer

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orderlines_controller.rb
class OrderlinesController < ApplicationController
  before_action :set_orderline, only: [:show, :edit, :update, :destroy]

  # GET /orderlines
  # GET /orderlines.json
  def index
    @orderlines = Orderline.all
  end

  # GET /orderlines/1
  # GET /orderlines/1.json
  def show
  end

  # GET /orderlines/new
  def new
    @orderline = Orderline.new
  end

  # GET /orderlines/1/edit
  def edit
  end

  # POST /orderlines
  # POST /orderlines.json
  def create
    @orderline = Orderline.new(orderline_params)

    respond_to do |format|
      if @orderline.save
        format.html { redirect_to @orderline, notice: 'Orderline was successfully created.' }
        format.json { render :show, status: :created, location: @orderline }
      else
        format.html { render :new }
        format.json { render json: @orderline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orderlines/1
  # PATCH/PUT /orderlines/1.json
  def update
    respond_to do |format|
      if @orderline.update(orderline_params)
        format.html { redirect_to @orderline, notice: 'Orderline was successfully updated.' }
        format.json { render :show, status: :ok, location: @orderline }
      else
        format.html { render :edit }
        format.json { render json: @orderline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orderlines/1
  # DELETE /orderlines/1.json
  def destroy
    @orderline.destroy
    respond_to do |format|
      format.html { redirect_to orderlines_url, notice: 'Orderline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orderline
      @orderline = Orderline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def orderline_params
      params.require(:orderline).permit(:delivery_address, :delivery_date, :remarks, :deposit_slip_status)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:tracking_id, :order_date, :total_bill)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new

    render 'new'
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      #render 'new'
      end
    end

    #render 'new'
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :classification, :kind, :size, :remarks)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orderlines_helper.rb
module OrderlinesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grechelle3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="headerimg">
	<div class="headerlink1">
		<%= link_to "home", root_path %>
	</div>
	<div class="headerlink2">
		products
	</div>
	<div class="headerlink3">
		my cart
	</div>
	<div class="headerlink4">
		verify
	</div>
</div>
<%= yield %>

</body>
</html>

app/views/orderlines/_form.html.erb
<%= form_for(@orderline) do |f| %>
  <% if @orderline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@orderline.errors.count, "error") %> prohibited this orderline from being saved:</h2>

      <ul>
      <% @orderline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :delivery_address %><br>
    <%= f.text_field :delivery_address %>
  </div>
  <div class="field">
    <%= f.label :delivery_date %><br>
    <%= f.datetime_select :delivery_date %>
  </div>
  <div class="field">
    <%= f.label :remarks %><br>
    <%= f.text_area :remarks %>
  </div>
  <div class="field">
    <%= f.label :deposit_slip_status %><br>
    <%= f.text_field :deposit_slip_status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orderlines/edit.html.erb
<h1>Editing Orderline</h1>

<%= render 'form' %>

<%= link_to 'Show', @orderline %> |
<%= link_to 'Back', orderlines_path %>

app/views/orderlines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orderlines</h1>

<table>
  <thead>
    <tr>
      <th>Delivery address</th>
      <th>Delivery date</th>
      <th>Remarks</th>
      <th>Deposit slip status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orderlines.each do |orderline| %>
      <tr>
        <td><%= orderline.delivery_address %></td>
        <td><%= orderline.delivery_date %></td>
        <td><%= orderline.remarks %></td>
        <td><%= orderline.deposit_slip_status %></td>
        <td><%= link_to 'Show', orderline %></td>
        <td><%= link_to 'Edit', edit_orderline_path(orderline) %></td>
        <td><%= link_to 'Destroy', orderline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Orderline', new_orderline_path %>

app/views/orderlines/new.html.erb
<h1>New Orderline</h1>

<%= render 'form' %>

<%= link_to 'Back', orderlines_path %>

app/views/orderlines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Delivery address:</strong>
  <%= @orderline.delivery_address %>
</p>

<p>
  <strong>Delivery date:</strong>
  <%= @orderline.delivery_date %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @orderline.remarks %>
</p>

<p>
  <strong>Deposit slip status:</strong>
  <%= @orderline.deposit_slip_status %>
</p>

<%= link_to 'Edit', edit_orderline_path(@orderline) %> |
<%= link_to 'Back', orderlines_path %>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tracking_id %><br>
    <%= f.number_field :tracking_id %>
  </div>
  <div class="field">
    <%= f.label :order_date %><br>
    <%= f.datetime_select :order_date %>
  </div>
  <div class="field">
    <%= f.label :total_bill %><br>
    <%= f.text_field :total_bill %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Tracking</th>
      <th>Order date</th>
      <th>Total bill</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.tracking_id %></td>
        <td><%= order.order_date %></td>
        <td><%= order.total_bill %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tracking:</strong>
  <%= @order.tracking_id %>
</p>

<p>
  <strong>Order date:</strong>
  <%= @order.order_date %>
</p>

<p>
  <strong>Total bill:</strong>
  <%= @order.total_bill %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :classification %><br>
    <%= f.text_field :classification %>
  </div>
  <div class="field">
    <%= f.label :kind %><br>
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :remarks %><br>
    <%= f.text_area :remarks %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Classification</th>
      <th>Type</th>
      <th>Size</th>
      <th>Remarks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.classification %></td>
        <td><%= product.kind %></td>
        <td><%= product.size %></td>
        <td><%= product.remarks %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Classification:</strong>
  <%= @product.classification %>
</p>

<p>
  <strong>Type:</strong>
  <%= @product.kind %>
</p>

<p>
  <strong>Size:</strong>
  <%= @product.size %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @product.remarks %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>